// Code generated by goctl. DO NOT EDIT.

package customer_other_details

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	customerOtherDetailsFieldNames          = builder.RawFieldNames(&CustomerOtherDetails{})
	customerOtherDetailsRows                = strings.Join(customerOtherDetailsFieldNames, ",")
	customerOtherDetailsRowsExpectAutoSet   = strings.Join(stringx.Remove(customerOtherDetailsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	customerOtherDetailsRowsWithPlaceHolder = strings.Join(stringx.Remove(customerOtherDetailsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	customerOtherDetailsModel interface {
		Insert(ctx context.Context, data *CustomerOtherDetails) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CustomerOtherDetails, error)
		Update(ctx context.Context, data *CustomerOtherDetails) error
		Delete(ctx context.Context, id int64) error
		FindOneByCustomerId(ctx context.Context, id int64) (*CustomerOtherDetails, error)
	}

	defaultCustomerOtherDetailsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CustomerOtherDetails struct {
		Id            int64     `db:"id"`
		Guid          string     `db:"guid"`
		ImageUrl      string    `db:"image_url"`
		WebImageUrl      string    `db:"web_image_url"`
		CustomerId    int64     `db:"customer_id"`
		MaritalStatus int64     `db:"marital_status"`
		Race          int64     `db:"race"`
		Updated       time.Time `db:"updated"`
		Created       time.Time `db:"created"`
		Active        int64     `db:"active"` // 0-Inactive,1-Active
	}
)

func newCustomerOtherDetailsModel(conn sqlx.SqlConn) *defaultCustomerOtherDetailsModel {
	return &defaultCustomerOtherDetailsModel{
		conn:  conn,
		table: "`customer_other_details`",
	}
}

func (m *defaultCustomerOtherDetailsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCustomerOtherDetailsModel) FindOne(ctx context.Context, id int64) (*CustomerOtherDetails, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", customerOtherDetailsRows, m.table)
	var resp CustomerOtherDetails
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCustomerOtherDetailsModel) Insert(ctx context.Context, data *CustomerOtherDetails) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, customerOtherDetailsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Guid, data.ImageUrl,data.WebImageUrl, data.CustomerId, data.MaritalStatus, data.Race, data.Updated, data.Created, data.Active)
	return ret, err
}

func (m *defaultCustomerOtherDetailsModel) Update(ctx context.Context, data *CustomerOtherDetails) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, customerOtherDetailsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Guid, data.ImageUrl,data.WebImageUrl, data.CustomerId, data.MaritalStatus, data.Race, data.Updated, data.Created, data.Active, data.Id)
	return err
}

func (m *defaultCustomerOtherDetailsModel) tableName() string {
	return m.table
}

func (m *defaultCustomerOtherDetailsModel) FindOneByCustomerId(ctx context.Context, id int64) (*CustomerOtherDetails, error) {
	query := fmt.Sprintf("select %s from %s where `customer_id` = ? and `active` = 1 limit 1", customerOtherDetailsRows, m.table)
	var resp CustomerOtherDetails
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}


